package yeong.chatting.util;

public enum ProtocolType {
	/** Client Request */
	REQUEST_LOGIN,
	REQUEST_REGISTRY,
	REQUEST_IDCHECK,
	REQUEST_WAITINGROOM_MEMBER,
	REQUEST_LOGOUT,
	REQUEST_CREATEROOM,
	REQUEST_ENTERROOM,
	REQUEST_EXITROOM,
	REQUEST_UPDATEWAITINGROOM,
	REQUEST_UPDATECHATTINGROOM,
	REQUEST_SEND,
	
	/** Server Response*/
	RESPONSE_LOGOUT,
	RESPONSE_IDCHECK,
	RESPONSE_REGISTRY_SUCCESS,
	RESPONSE_REGISTRY_FAIL,
	RESPONSE_LOGIN_SUCCESS,
	RESPONSE_LOGIN_FAIL,
	RESPONSE_WAITINGROOM_MEMBER,
	RESPONSE_CREATEROOM,
	RESPONSE_CREATEROOM_FAIL,
	RESPONSE_ENTERROOM_SUCCESS,
	RESPONSE_ENTERROOM_FAIL,
	RESPONSE_EXITROOM,
	RESPONSE_EXITROOM_HOST,
	
	RESPONSE_UPDATEWAITINGROOM,
	RESPONSE_UPDATECHATTINGROOM,
	
	RESPONSE_FORCEDEXIT,

	RESPONSE_SEND,
	CLOSE
//	아직 미구현
//	SECRET_MESSAGE,
}
