package yeong.chatting.util;

public enum ProtocolType {
	/** Client Request */
	REQUEST_LOGIN,
	REQUEST_REGISTRY,
	REQUEST_WAITINGROOM_MEMBER,
		
	/** Server Response*/
	RESPONSE_REGISTRY_SUCCESS,
	RESPONSE_REGISTRY_FAIL,
	RESPONSE_LOGIN_SUCCESS,
	RESPONSE_LOGIN_FAIL,
	RESPONSE_WAITINROOM_MEMBER,
	
	
	LOGOUT,
	ENTER_ROOM,
	SEND_MESSAGE,
	SECRET_MESSAGE
}
