package yeong.chatting.util;

public enum ProtocolType {
	/** Client Request */
	REQUEST_LOGIN,
	REQUEST_REGISTRY,
	REQUEST_WAITINGROOM_MEMBER,
	REQUEST_LOGOUT,
	
	/** Server Response*/
	RESPONSE_LOGOUT,
	RESPONSE_REGISTRY_SUCCESS,
	RESPONSE_REGISTRY_FAIL,
	RESPONSE_LOGIN_SUCCESS,
	RESPONSE_LOGIN_FAIL,
	RESPONSE_WAITINGROOM_MEMBER,
	

	SEND_MESSAGE,
	SECRET_MESSAGE
}
